name: savetheplanet
description: Retro feeling planet defense game
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  google_fonts:
  provider:
  audioplayers:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/planet/bw-map.png
    - assets/actors/corona.png
    - assets/sounds/fire.mp3
    - assets/sounds/explosion.mp3
    - assets/sounds/failure.mp3
    - assets/sounds/powerup.mp3
    - assets/sounds/saved.mp3
    - assets/music/music.mp3
    - assets/music/menu-music.mp3
